<?php

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

0 + 1 = 1
1 + 1 = 2
1 + 2 = 3
2 + 3 = 5
3 + 5 = 8
5 + 8 = 13

*/

$array = array();
$a = 0;
$b = 1;
for($i = 0; $i <= $b; $i++){
	$sum = $a + $b;
	$a = $b;
	$b = $sum;		
	if($b < 4000000){
		if($b % 2 == 0){
			$array[] = $b;
		}
	} else {
		break;
	}

}

print_r($array);
echo "Sum is: " . array_sum($array) . "\n";



